### ISSUE TITLE
Zowe explorer for CICS secure credentials issue

### ISSUE THREAD

**Issue by jt-nti** [jt-nti/hello-cics#10]
Currently seeing an error from the zowe explorer for CICS extension in vscode when clicking the + icon…

```
{"stack":"ProfInfoErr: Failed to initialize secure credential manager at ProfileInfo.<anonymous> (/home/vscode/.vscode-server/extensions/zowe.cics-extension-for-zowe-2.3.0/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/config/src/ProfileInfo.js:829:23) at Generator.throw (<anonymous>) at rejected (/home/vscode/.vscode-server/extensions/zowe.cics-extension-for-zowe-2.3.0/node_modules/@zowe/cli/node_modules/@zowe/imperative/lib/config/src/ProfileInfo.js:16:65)","mDetails":{},"mMessage":"Failed to initialize secure credential manager","mItemsInError":[],"name":"ProfInfoErr"}
```

Secure credentials are working ok for data sets, uss and jobs. The zowe cli is also happy so the team configuration file is presumably ok, e.g.

```shell
$ zowe cics get resource CICSTask --rfj | jq .data.response.records.cicstask.runstatus
"RUNNING"
```

Tried rolling back to [v2.6.1](https://github.com/zowe/vscode-extension-for-zowe/releases/tag/v2.6.1) of the zowe explorer extension but saw the same problem.

See zowe/vscode-extension-for-cics#324

**Comment by jt-nti** [comment]
Hmmm, thought this might be working by now but no luck so far.

<img width="456" alt="Image" src="https://github.com/user-attachments/assets/f6634235-7230-4c99-abe2-d538c1c79204" />

A few related resources...
- https://github.com/zowe/zowe-explorer-vscode/wiki/Usage-in-Remote-Environments
- https://github.com/kdrkrst/zowe-remote-dev-container-config-doc
- https://docs.zowe.org/stable/user-guide/ze-usage#using-zowe-explorer-in-remote-environments
- https://medium.com/zowe/custom-credential-managers-in-zowe-explorer-b37faeee4c29
- https://medium.com/zowe/running-zowe-cli-on-jenkins-with-docker-7fd35d4211d0
- https://code.visualstudio.com/updates/v1_83#_keytar-removed-from-vs-code
- https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues
- https://github.com/zowe/zowe-explorer-vscode/issues/2348
- https://github.com/IBM/db2forzosdeveloperextension-about/issues/63

**Comment by jt-nti** [comment]
```
vscode ➜ /workspaces/hello-cics (new-devcontainer) $ dpkg -l | libsecret-1-0
bash: libsecret-1-0: command not found
vscode ➜ /workspaces/hello-cics (new-devcontainer) $ dpkg -l | grep libsecret-1-0
ii  libsecret-1-0:arm64           0.20.5-2                                arm64        Secret store
vscode ➜ /workspaces/hello-cics (new-devcontainer) $ dpkg -l | grep dbus-x11
ii  dbus-x11                      1.12.20-2ubuntu4.1                      arm64        simple interprocess messaging system (X11 deps)
vscode ➜ /workspaces/hello-cics (new-devcontainer) $ dpkg -l | grep gnome-keyring
ii  gnome-keyring                 40.0-3ubuntu3                           arm64        GNOME keyring services (daemon and tools)
ii  gnome-keyring-pkcs11:arm64    40.0-3ubuntu3                           arm64        GNOME keyring module for the PKCS#11 module loading library
ii  libpam-gnome-keyring:arm64    40.0-3ubuntu3                           arm64        PAM module to unlock the GNOME keyring upon login
vscode ➜ /workspaces/hello-cics (new-devcontainer) $ gnome-keyring-daemon
GNOME_KEYRING_CONTROL=/home/vscode/.cache/keyring-I5NF02
SSH_AUTH_SOCK=/home/vscode/.cache/keyring-I5NF02/ssh
```

**Comment by jt-nti** [comment]
Currently reading https://www.baeldung.com/linux/systemd-session-dbus-headless-setup !!!

**Comment by jt-nti** [comment]
See jt-nti/zxplore#2 for a fix!
